spring.application.name=KeamanInformasi
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration


# Basic SpringDoc configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Database configuration (using H2 in-memory database by default)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Enable H2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Add Jakarta Bean Validation dependency
spring.mvc.problemdetails.enabled=true

# Logging for troubleshooting
logging.level.org.springdoc=DEBUG
logging.level.org.springframework.web=DEBUG

